Projet/Controllers/CompetencesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Projet.Models;

namespace Projet.Controllers
{
    public class CompetencesController : Controller
    {
        private readonly ProjetContext _context;

        public CompetencesController(ProjetContext context)
        {
            _context = context;
        }

        // GET: Competences
        public async Task<IActionResult> Index(string searchString, string sortOrder)
        {
            
            var query = _context.Competences.AsQueryable();

            
            if (!string.IsNullOrEmpty(searchString))
            {
                query = query.Where(c => c.Nom.Contains(searchString));
            }

            
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            switch (sortOrder)
            {
                case "name_desc":
                    query = query.OrderByDescending(c => c.Nom);
                    break;
                default:
                    query = query.OrderBy(c => c.Nom);
                    break;
            }

            var competences = await query.ToListAsync();

            
            var topCompetences = await _context.CompetenceSouhaitees
                .Include(cs => cs.Competence)
                .GroupBy(cs => cs.Competence.Nom)
                .Select(g => new { Nom = g.Key, Nombre = g.Count() })
                .OrderByDescending(x => x.Nombre).Take(5).ToListAsync();

            ViewBag.TopLabels = topCompetences.Select(x => x.Nom).ToList();
            ViewBag.TopData = topCompetences.Select(x => x.Nombre).ToList();

            
            ViewData["CurrentFilter"] = searchString;

            return View(competences);
        }

        // GET: Competences/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var competence = await _context.Competences
                .FirstOrDefaultAsync(m => m.Id == id);
            if (competence == null)
            {
                return NotFound();
            }

            return View(competence);
        }

        // GET: Competences/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Competences/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nom")] Competence competence)
        {
            if (ModelState.IsValid)
            {
                _context.Add(competence);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(competence);
        }

        // GET: Competences/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var competence = await _context.Competences.FindAsync(id);
            if (competence == null)
            {
                return NotFound();
            }
            return View(competence);
        }

        // POST: Competences/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nom")] Competence competence)
        {
            if (id != competence.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(competence);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompetenceExists(competence.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(competence);
        }

        // GET: Competences/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var competence = await _context.Competences
                .FirstOrDefaultAsync(m => m.Id == id);
            if (competence == null)
            {
                return NotFound();
            }

            return View(competence);
        }

        // POST: Competences/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var competence = await _context.Competences.FindAsync(id);
            if (competence != null)
            {
                _context.Competences.Remove(competence);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompetenceExists(int id)
        {
            return _context.Competences.Any(e => e.Id == id);
        }
    }
}

Projet/Controllers/OffresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Projet.Models;

namespace Projet.Controllers
{
    public class OffresController : Controller
    {
        private readonly ProjetContext _context;

        public OffresController(ProjetContext context)
        {
            _context = context;
        }

        // GET: Offres
        public async Task<IActionResult> Index(string searchString, int? posteId)
        {
            
            var query = _context.Offres.Include(o => o.Poste).AsQueryable();

            
            if (!string.IsNullOrEmpty(searchString))
            {
                query = query.Where(o => o.Titre.Contains(searchString) || o.VilleCible.Contains(searchString));
            }

            
            if (posteId.HasValue)
            {
                query = query.Where(o => o.PosteId == posteId);
            }

            
            var offres = await query.OrderByDescending(o => o.DateCreation).ToListAsync();

            

            
            ViewBag.Postes = await _context.Postes.OrderBy(p => p.Intitule).ToListAsync();

            
            var statsVilles = offres
                .GroupBy(o => o.VilleCible)
                .Select(g => new { Ville = g.Key, Nombre = g.Count() })
                .ToList();

            ViewBag.VillesLabels = statsVilles.Select(s => s.Ville).ToList();
            ViewBag.VillesData = statsVilles.Select(s => s.Nombre).ToList();

            
            ViewData["CurrentFilter"] = searchString;
            ViewData["CurrentPoste"] = posteId;

            return View(offres);
        }

        // GET: Offres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offre = await _context.Offres
                .Include(o => o.Poste)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (offre == null)
            {
                return NotFound();
            }

            return View(offre);
        }

        // GET: Offres/Create
        public IActionResult Create()
        {
            ViewData["PosteId"] = new SelectList(_context.Postes, "Id", "Id");
            return View();
        }

        // POST: Offres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titre,Description,DateCreation,VilleCible,CodePostalCible,PosteId")] Offre offre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(offre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PosteId"] = new SelectList(_context.Postes, "Id", "Id", offre.PosteId);
            return View(offre);
        }

        // GET: Offres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offre = await _context.Offres.FindAsync(id);
            if (offre == null)
            {
                return NotFound();
            }
            ViewData["PosteId"] = new SelectList(_context.Postes, "Id", "Id", offre.PosteId);
            return View(offre);
        }

        // POST: Offres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titre,Description,DateCreation,VilleCible,CodePostalCible,PosteId")] Offre offre)
        {
            if (id != offre.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(offre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OffreExists(offre.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PosteId"] = new SelectList(_context.Postes, "Id", "Id", offre.PosteId);
            return View(offre);
        }

        // GET: Offres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offre = await _context.Offres
                .Include(o => o.Poste)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (offre == null)
            {
                return NotFound();
            }

            return View(offre);
        }

        // POST: Offres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var offre = await _context.Offres.FindAsync(id);
            if (offre != null)
            {
                _context.Offres.Remove(offre);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OffreExists(int id)
        {
            return _context.Offres.Any(e => e.Id == id);
        }
    }
}

Projet/Controllers/ScoringController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Projet.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Projet.Controllers
{
    public class ScoringController : Controller
    {
        private readonly ProjetContext _context;

        public ScoringController(ProjetContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {

            var offres = _context.Offres.Include(o => o.Poste).ToList();
            return View(offres);
        }


        public IActionResult Calculer(int id)
        {
            
            var offre = _context.Offres
                .Include(o => o.CompetenceSouhaitees)
                    .ThenInclude(cs => cs.Competence)
                .Include(o => o.ParametreScoring)
                .FirstOrDefault(o => o.Id == id);

            if (offre == null) return NotFound();

            
            int poidsComp = offre.ParametreScoring?.PoidsCompetences ?? 60;
            int poidsExp = offre.ParametreScoring?.PoidsExperience ?? 20;
            int poidsLoc = offre.ParametreScoring?.PoidsLocalisation ?? 20;

            
            var candidats = _context.Personnes
                .Include(p => p.CompetenceAcquises)
                    .ThenInclude(ca => ca.Competence) 
                .ToList();

            var resultats = new List<CandidateMatchViewModel>();

            
            foreach (var candidat in candidats)
            {
                var vm = new CandidateMatchViewModel
                {
                    CandidatId = candidat.Id,
                    NomComplet = $"{candidat.Prenom} {candidat.Nom}",
                    JobActuel = candidat.Ville ?? "Ville inconnue"
                };

                
                double totalPointsCompetences = 0;
                double maxPointsCompetences = 0;

                foreach (var compRequise in offre.CompetenceSouhaitees)
                {
                    maxPointsCompetences += 100;

                    var compCandidat = candidat.CompetenceAcquises
                        .FirstOrDefault(c => c.CompetenceId == compRequise.CompetenceId);

                    if (compCandidat != null)
                    {
                        
                        double niveauCandidat = (double)(compCandidat.Niveau ?? 0);
                        double niveauRequis = (double)(compRequise.NiveauRequis ?? 1); 

                        double ratio = niveauCandidat / niveauRequis;

                        if (ratio > 1) ratio = 1;

                        totalPointsCompetences += (ratio * 100);

                        if (ratio >= 1)
                            vm.DetailsPositifs.Add($"{compRequise.Competence?.Nom ?? "Inconnu"} (Niveau OK)");
                        else
                            vm.DetailsNegatifs.Add($"{compRequise.Competence?.Nom ?? "Inconnu"} (Niveau faible)");
                    }
                    else
                    {
                        vm.DetailsNegatifs.Add($"{compRequise.Competence?.Nom ?? "Inconnu"} (Manquante)");
                    }
                }

                
                double scoreBrutComp = (maxPointsCompetences > 0)
                    ? (totalPointsCompetences / maxPointsCompetences) * 100
                    : 0;

                vm.ScoreCompetences = (int)scoreBrutComp;


                int scoreBrutExp = 0;

                int xpCandidat = candidat.AnneesExperienceTotal ?? 0; 

                if (xpCandidat >= 5) scoreBrutExp = 100;
                else if (xpCandidat >= 2) scoreBrutExp = 70;
                else scoreBrutExp = 30;

                vm.ScoreExperience = scoreBrutExp;


                int scoreBrutLoc = 0;
                string villeOffre = offre.VilleCible?.Trim().ToLower() ?? "";
                string villeCandidat = candidat.Ville?.Trim().ToLower() ?? "";

                if (!string.IsNullOrEmpty(villeOffre) && !string.IsNullOrEmpty(villeCandidat))
                {
                    if (villeOffre == villeCandidat)
                    {
                        scoreBrutLoc = 100;
                        vm.IsLocalisationOk = true;
                        vm.DetailsPositifs.Add("Même ville");
                    }
                    else
                    {
                        vm.DetailsNegatifs.Add($"Ville différente ({candidat.Ville})");
                    }
                }
                vm.ScoreLocalisation = scoreBrutLoc;


                double noteFinale = (scoreBrutComp * poidsComp) + (scoreBrutExp * poidsExp) + (scoreBrutLoc * poidsLoc);


                double sommePoids = poidsComp + poidsExp + poidsLoc;
                if (sommePoids == 0) sommePoids = 1;

                vm.ScoreGlobal = (int)(noteFinale / sommePoids);


                bool fautExclure = offre.ParametreScoring?.ExclureSiVilleDiff ?? false;

                if (fautExclure && scoreBrutLoc == 0)
                {
                    vm.ScoreGlobal = 0;
                    vm.DetailsNegatifs.Insert(0, "⛔ DISQUALIFIÉ (Mauvaise Ville)");
                }

                resultats.Add(vm);
            }

            var classement = resultats.OrderByDescending(r => r.ScoreGlobal).ToList();
            ViewBag.TitreOffre = offre.Titre;

            return View(classement);
        }
    }
}

Projet/Views/Home/Index.cshtml
@model Projet.Models.HomeDashboardViewModel

@{
    ViewData["Title"] = "Tableau de Bord RH";
}

<div class="row mb-4 align-items-center">
    <div class="col-md-8">
        <h2 class="fw-bold text-dark mb-0">Tableau de Bord</h2>
        <p class="text-muted small">Vue d'ensemble de votre activité de recrutement.</p>
    </div>
    <div class="col-md-4 text-end">
        <a asp-controller="Scoring" asp-action="Index" class="btn btn-primary-gradient shadow-sm px-4">
            <i class="fas fa-magic me-2"></i>Lancer un Matching
        </a>
    </div>
</div>

<div class="row g-4 mb-5">
    <div class="col-md-4">
        <div class="card border-0 shadow-sm h-100 overflow-hidden">
            <div class="card-body p-4 position-relative">
                <div class="d-flex justify-content-between align-items-start">
                    <div>
                        <p class="text-uppercase fw-bold text-muted small mb-1">Offres Ouvertes</p>
                        <h2 class="display-5 fw-bold text-primary mb-0">@Model.NbOffres</h2>
                    </div>
                    <div class="p-3 rounded-3 bg-primary bg-opacity-10 text-primary">
                        <i class="fas fa-briefcase fa-2x"></i>
                    </div>
                </div>
                <div class="mt-4">
                    <a asp-controller="Offres" asp-action="Index" class="small text-decoration-none fw-bold">Gérer les offres <i class="fas fa-arrow-right ms-1"></i></a>
                </div>
                <div class="position-absolute bg-primary rounded-circle" style="width: 150px; height: 150px; top: -50px; right: -50px; opacity: 0.05;"></div>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card border-0 shadow-sm h-100 overflow-hidden">
            <div class="card-body p-4 position-relative">
                <div class="d-flex justify-content-between align-items-start">
                    <div>
                        <p class="text-uppercase fw-bold text-muted small mb-1">Vivier Talents</p>
                        <h2 class="display-5 fw-bold text-success mb-0">@Model.NbCandidats</h2>
                    </div>
                    <div class="p-3 rounded-3 bg-success bg-opacity-10 text-success">
                        <i class="fas fa-users fa-2x"></i>
                    </div>
                </div>
                <div class="mt-4">
                    <a asp-controller="Personnes" asp-action="Index" class="small text-decoration-none fw-bold text-success">Voir la liste <i class="fas fa-arrow-right ms-1"></i></a>
                </div>
                <div class="position-absolute bg-success rounded-circle" style="width: 150px; height: 150px; top: -50px; right: -50px; opacity: 0.05;"></div>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card border-0 shadow-sm h-100 overflow-hidden">
            <div class="card-body p-4 position-relative">
                <div class="d-flex justify-content-between align-items-start">
                    <div>
                        <p class="text-uppercase fw-bold text-muted small mb-1">Tags Compétences</p>
                        <h2 class="display-5 fw-bold text-warning mb-0">@Model.NbCompetences</h2>
                    </div>
                    <div class="p-3 rounded-3 bg-warning bg-opacity-10 text-warning">
                        <i class="fas fa-tags fa-2x"></i>
                    </div>
                </div>
                <div class="mt-4">
                    <a asp-controller="Competences" asp-action="Index" class="small text-decoration-none fw-bold text-warning">Catalogue <i class="fas fa-arrow-right ms-1"></i></a>
                </div>
                <div class="position-absolute bg-warning rounded-circle" style="width: 150px; height: 150px; top: -50px; right: -50px; opacity: 0.05;"></div>
            </div>
        </div>
    </div>
</div>

<div class="row g-4 mb-4">
    <div class="col-lg-8">
        <div class="card border-0 shadow-sm h-100">
            <div class="card-header bg-white border-0 pt-4 px-4 d-flex justify-content-between">
                <h6 class="fw-bold mb-0">📊 Répartition des Offres par Métier</h6>
            </div>
            <div class="card-body px-4 pb-4">
                <div style="height: 300px;">
                    <canvas id="chartMetiers"></canvas>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="card border-0 shadow-sm h-100">
            <div class="card-header bg-white border-0 pt-4 px-4">
                <h6 class="fw-bold mb-0">🎓 Niveaux d'Expérience</h6>
            </div>
            <div class="card-body d-flex align-items-center justify-content-center position-relative">
                <div style="height: 220px; width: 100%;">
                    <canvas id="chartExp"></canvas>
                </div>
                <div class="position-absolute text-center" style="pointer-events: none;">
                    <span class="d-block display-6 fw-bold text-muted">@Model.NbCandidats</span>
                    <span class="small text-uppercase text-muted" style="font-size: 0.65rem;">Profils</span>
                </div>
            </div>
            <div class="card-footer bg-white border-0 text-center pb-4">
                <small class="text-muted">Répartition Junior / Confirmé / Senior</small>
            </div>
        </div>
    </div>
</div>

<div class="row g-4">
    <div class="col-lg-6">
        <div class="card border-0 shadow-sm h-100">
            <div class="card-header bg-white border-0 pt-4 px-4 d-flex justify-content-between align-items-center">
                <h6 class="fw-bold mb-0">⚡ Activités Récentes</h6>
                <span class="badge bg-light text-secondary border">Temps réel</span>
            </div>
            <div class="card-body p-0">
                <div class="list-group list-group-flush mt-2">
                    @if (Model.Activites.Any())
                    {
                        @foreach (var item in Model.Activites)
                        {
                            var isOffre = item.Type == "Offre";
                            var icon = isOffre ? "fa-plus" : "fa-user";
                            var color = isOffre ? "bg-primary-subtle text-primary" : "bg-success-subtle text-success";
                            var controller = isOffre ? "Offres" : "Personnes";

                            <a asp-controller="@controller" asp-action="Details" asp-route-id="@item.Id" class="list-group-item list-group-item-action border-0 px-4 py-3 d-flex align-items-center">
                                <div class="rounded-circle p-2 me-3 d-flex align-items-center justify-content-center @color" style="width: 35px; height: 35px;">
                                    <i class="fas @icon small"></i>
                                </div>
                                <div>
                                    <div class="fw-bold text-dark small">@item.Titre</div>
                                    <div class="text-muted" style="font-size: 0.8rem;">@item.SousTitre</div>
                                </div>
                                <small class="ms-auto text-muted" style="font-size: 0.7rem;">#@item.Id</small>
                            </a>
                        }
                    }
                    else
                    {
                        <div class="text-center py-4 text-muted small">Aucune activité récente.</div>
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card border-0 shadow-sm h-100 bg-primary text-white" style="background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);">
            <div class="card-body p-5 d-flex flex-column justify-content-center text-center">
                <h3 class="fw-bold mb-3">Besoin d'aller vite ?</h3>
                <p class="mb-4 opacity-75">Utilisez les raccourcis pour alimenter votre base de données.</p>

                <div class="d-flex justify-content-center gap-3">
                    <a asp-controller="Offres" asp-action="Create" class="btn btn-light text-primary fw-bold shadow-sm">
                        <i class="fas fa-plus-circle me-2"></i>Nouvelle Offre
                    </a>
                    <a asp-controller="Personnes" asp-action="Create" class="btn btn-outline-light fw-bold">
                        <i class="fas fa-user-plus me-2"></i>Nouveau Candidat
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    document.addEventListener("DOMContentLoaded", function() {

        // --- GRAPHIQUE 1 : OFFRES (BARRES) ---
        const ctxMetiers = document.getElementById('chartMetiers').getContext('2d');
        const labelsMetiers = @Html.Raw(Json.Serialize(Model.LabelsMetiers));
        const dataMetiers = @Html.Raw(Json.Serialize(Model.DataMetiers));

        // Dégradé bleu
        let gradientBar = ctxMetiers.createLinearGradient(0, 0, 0, 300);
        gradientBar.addColorStop(0, '#4e73df');
        gradientBar.addColorStop(1, '#224abe');

        new Chart(ctxMetiers, {
            type: 'bar',
            data: {
                labels: labelsMetiers,
                datasets: [{
                    label: 'Postes',
                    data: dataMetiers,
                    backgroundColor: gradientBar,
                    borderRadius: 5,
                    barThickness: 30
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: { legend: { display: false } },
                scales: {
                    y: { beginAtZero: true, grid: { borderDash: [5, 5] } },
                    x: { grid: { display: false } }
                }
            }
        });

        // --- GRAPHIQUE 2 : EXPÉRIENCE (DONUT) ---
        const ctxExp = document.getElementById('chartExp').getContext('2d');
        const dataExp = @Html.Raw(Json.Serialize(Model.DataExperience)); // [Junior, Confirme, Senior]

        new Chart(ctxExp, {
            type: 'doughnut',
            data: {
                labels: ['Junior (<2 ans)', 'Confirmé (2-5 ans)', 'Senior (5+ ans)'],
                datasets: [{
                    data: dataExp,
                    backgroundColor: ['#d1d3e2', '#36b9cc', '#1cc88a'], // Gris, Cyan, Vert
                    borderWidth: 0,
                    hoverOffset: 10
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                cutout: '75%', // Trou du donut large
                plugins: {
                    legend: { position: 'bottom', labels: { usePointStyle: true, boxWidth: 8 } }
                }
            }
        });
    });
</script>